version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:tucontraseña@db:5432/django_db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=tucontraseña
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: