

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9217"
    volumes:
      - .:/usr/app
    ports:
      - "9217:9217"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:quack@db:7821/django_db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=quack
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django_db
      - POSTGRES_PORT=7821
    ports:
      - "7821:5432"

volumes:
  postgres_data: