# Generated by Django 5.2.1 on 2025-05-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='materiales',
            new_name='material',
        ),
    ]
