# Generated by Django 5.2.1 on 2025-05-12 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_rename_materiales_proveedor_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='material',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tiempo_de_respuesta',
            field=models.IntegerField(help_text='Tiempo de respuesta en días'),
        ),
    ]
