# Generated by Django 5.2.1 on 2025-05-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_material_alter_proveedor_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='precio',
            field=models.DecimalField(decimal_places=0, help_text='Precio por 100 kg', max_digits=10),
        ),
    ]
