# Generated by Django 5.2.1 on 2025-07-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_requisicion_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
